export const DATA_STORES = ['entities','relations','media','settings','clues','reveals','knowledge','mapVersions','mapMarkers','workspace'];
export const TABLE = { entities:'entities', relations:'relations', media:'media', settings:'settings', clues:'clues', reveals:'reveals', knowledge:'knowledge', mapVersions:'map_versions', mapMarkers:'map_markers', workspace:'workspace' };

function safeJson(value,fallback){ try{return JSON.parse(value);}catch{return fallback;} }
function now(){ return new Date().toISOString(); }

export function rowToRecord(store,row){
  if(!row) return null;
  if(store==='entities') return {id:row.id,type:row.type,name:row.name,summary:row.summary||'',status:row.status,tags:safeJson(row.tags_json,[]),favorite:Boolean(row.favorite),fields:safeJson(row.fields_json,{}),notes:row.notes||'',archivedAt:row.archived_at||null,createdAt:row.created_at,updatedAt:row.updated_at};
  if(store==='relations') return {id:row.id,fromId:row.from_id,toId:row.to_id,type:row.type,status:row.status||'Canon',note:row.note||'',generatedParent:Boolean(row.generated_parent),eraId:row.era_id||null,activeFrom:row.active_from||'',activeTo:row.active_to||'',createdAt:row.created_at,updatedAt:row.updated_at||row.created_at};
  if(store==='settings') return {key:row.key,value:safeJson(row.value_json,{}),updatedAt:row.updated_at||''};
  if(store==='media') return {id:row.id,name:row.name,title:row.title,mime:row.mime,size:Number(row.size)||0,r2Key:row.r2_key,tags:safeJson(row.tags_json,[]),entityIds:safeJson(row.entity_ids_json,[]),createdAt:row.created_at,updatedAt:row.updated_at||row.created_at,url:`/api/media/${encodeURIComponent(row.id)}/content`};
  if(store==='clues') return {id:row.id,mysteryId:row.mystery_id,mysteryIds:safeJson(row.mystery_ids_json,[]),label:row.label||'',kind:row.kind||'',description:row.description||'',storyEntityId:row.story_entity_id||null,visibility:row.visibility||'',firstRead:row.first_read||'',trueInterpretation:row.true_interpretation||'',order:row.order_value||'',createdAt:row.created_at,updatedAt:row.updated_at};
  if(store==='reveals') return {id:row.id,title:row.title||'',summary:row.summary||'',readerKnowledge:row.reader_knowledge||'',mysteryId:row.mystery_id||null,targetEntityId:row.target_entity_id||null,bookId:row.book_id||null,partId:row.part_id||null,chapterId:row.chapter_id||null,sceneId:row.scene_id||null,createdAt:row.created_at,updatedAt:row.updated_at};
  if(store==='knowledge') return {id:row.id,subjectEntityId:row.subject_entity_id,knowerKind:row.knower_kind,knowerEntityId:row.knower_entity_id||null,state:row.state,belief:row.belief||'',truthNote:row.truth_note||'',storyEntityId:row.story_entity_id||null,createdAt:row.created_at,updatedAt:row.updated_at};
  if(store==='mapVersions') return {id:row.id,mapId:row.map_id,mediaId:row.media_id,label:row.label||'',variant:row.variant||'',effectiveDate:row.effective_date||'',notes:row.notes||'',createdAt:row.created_at,updatedAt:row.updated_at||row.created_at};
  if(store==='mapMarkers') return {id:row.id,mapVersionId:row.map_version_id,locationId:row.location_id,x:Number(row.x),y:Number(row.y),label:row.label||'',category:row.category||'',icon:row.icon||'',customMediaId:row.custom_media_id||null,tags:safeJson(row.tags_json,[]),activeFrom:row.active_from||'',activeTo:row.active_to||'',layerId:row.layer_id||null,factionId:row.faction_id||null,bookIds:safeJson(row.book_ids_json,[]),storyRelevance:row.story_relevance||'',active:row.active!==0,createdAt:row.created_at,updatedAt:row.updated_at||row.created_at};
  if(store==='workspace') return {id:row.id,kind:row.kind,title:row.title||'',data:safeJson(row.data_json,{}),createdAt:row.created_at,updatedAt:row.updated_at};
  return null;
}

export function upsertStatement(env,store,r){
  if(store==='entities') return env.DB.prepare(`INSERT INTO entities (id,type,name,summary,status,tags_json,favorite,fields_json,notes,archived_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET type=excluded.type,name=excluded.name,summary=excluded.summary,status=excluded.status,tags_json=excluded.tags_json,favorite=excluded.favorite,fields_json=excluded.fields_json,notes=excluded.notes,archived_at=excluded.archived_at,created_at=excluded.created_at,updated_at=excluded.updated_at`).bind(r.id,r.type,r.name,r.summary||'',r.status,JSON.stringify(r.tags||[]),r.favorite?1:0,JSON.stringify(r.fields||{}),r.notes||'',r.archivedAt||null,r.createdAt||now(),r.updatedAt||now());
  if(store==='relations') return env.DB.prepare(`INSERT INTO relations (id,from_id,to_id,type,status,note,generated_parent,created_at,era_id,active_from,active_to,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET from_id=excluded.from_id,to_id=excluded.to_id,type=excluded.type,status=excluded.status,note=excluded.note,generated_parent=excluded.generated_parent,era_id=excluded.era_id,active_from=excluded.active_from,active_to=excluded.active_to,updated_at=excluded.updated_at`).bind(r.id,r.fromId,r.toId,r.type,r.status||'Canon',r.note||'',r.generatedParent?1:0,r.createdAt||now(),r.eraId||null,r.activeFrom||'',r.activeTo||'',r.updatedAt||now());
  if(store==='settings') return env.DB.prepare(`INSERT INTO settings (key,value_json,updated_at) VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at`).bind(r.key,JSON.stringify(r.value||{}),r.updatedAt||now());
  if(store==='media') return env.DB.prepare(`INSERT INTO media (id,name,title,mime,size,r2_key,tags_json,entity_ids_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,title=excluded.title,mime=excluded.mime,size=excluded.size,r2_key=excluded.r2_key,tags_json=excluded.tags_json,entity_ids_json=excluded.entity_ids_json,created_at=excluded.created_at,updated_at=excluded.updated_at`).bind(r.id,r.name||'file',r.title||r.name||'file',r.mime||'application/octet-stream',Number(r.size)||0,r.r2Key,JSON.stringify(r.tags||[]),JSON.stringify(r.entityIds||[]),r.createdAt||now(),r.updatedAt||now());
  if(store==='clues') return env.DB.prepare(`INSERT INTO clues (id,mystery_id,mystery_ids_json,label,kind,description,story_entity_id,visibility,first_read,true_interpretation,order_value,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET mystery_id=excluded.mystery_id,mystery_ids_json=excluded.mystery_ids_json,label=excluded.label,kind=excluded.kind,description=excluded.description,story_entity_id=excluded.story_entity_id,visibility=excluded.visibility,first_read=excluded.first_read,true_interpretation=excluded.true_interpretation,order_value=excluded.order_value,updated_at=excluded.updated_at`).bind(r.id,r.mysteryId,JSON.stringify(r.mysteryIds||[]),r.label||'',r.kind||'',r.description||'',r.storyEntityId||null,r.visibility||'',r.firstRead||'',r.trueInterpretation||'',String(r.order??''),r.createdAt||now(),r.updatedAt||now());
  if(store==='reveals') return env.DB.prepare(`INSERT INTO reveals (id,title,summary,reader_knowledge,mystery_id,target_entity_id,book_id,part_id,chapter_id,scene_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,summary=excluded.summary,reader_knowledge=excluded.reader_knowledge,mystery_id=excluded.mystery_id,target_entity_id=excluded.target_entity_id,book_id=excluded.book_id,part_id=excluded.part_id,chapter_id=excluded.chapter_id,scene_id=excluded.scene_id,updated_at=excluded.updated_at`).bind(r.id,r.title||'',r.summary||'',r.readerKnowledge||'',r.mysteryId||null,r.targetEntityId||null,r.bookId||null,r.partId||null,r.chapterId||null,r.sceneId||null,r.createdAt||now(),r.updatedAt||now());
  if(store==='knowledge') return env.DB.prepare(`INSERT INTO knowledge (id,subject_entity_id,knower_kind,knower_entity_id,state,belief,truth_note,story_entity_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET subject_entity_id=excluded.subject_entity_id,knower_kind=excluded.knower_kind,knower_entity_id=excluded.knower_entity_id,state=excluded.state,belief=excluded.belief,truth_note=excluded.truth_note,story_entity_id=excluded.story_entity_id,updated_at=excluded.updated_at`).bind(r.id,r.subjectEntityId,r.knowerKind,r.knowerEntityId||null,r.state,r.belief||'',r.truthNote||'',r.storyEntityId||null,r.createdAt||now(),r.updatedAt||now());
  if(store==='mapVersions') return env.DB.prepare(`INSERT INTO map_versions (id,map_id,media_id,label,variant,effective_date,notes,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET map_id=excluded.map_id,media_id=excluded.media_id,label=excluded.label,variant=excluded.variant,effective_date=excluded.effective_date,notes=excluded.notes,updated_at=excluded.updated_at`).bind(r.id,r.mapId,r.mediaId,r.label||'',r.variant||'',r.effectiveDate||'',r.notes||'',r.createdAt||now(),r.updatedAt||now());
  if(store==='mapMarkers') return env.DB.prepare(`INSERT INTO map_markers (id,map_version_id,location_id,x,y,label,category,icon,custom_media_id,tags_json,active_from,active_to,layer_id,faction_id,book_ids_json,story_relevance,active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET map_version_id=excluded.map_version_id,location_id=excluded.location_id,x=excluded.x,y=excluded.y,label=excluded.label,category=excluded.category,icon=excluded.icon,custom_media_id=excluded.custom_media_id,tags_json=excluded.tags_json,active_from=excluded.active_from,active_to=excluded.active_to,layer_id=excluded.layer_id,faction_id=excluded.faction_id,book_ids_json=excluded.book_ids_json,story_relevance=excluded.story_relevance,active=excluded.active,updated_at=excluded.updated_at`).bind(r.id,r.mapVersionId,r.locationId,Number(r.x),Number(r.y),r.label||'',r.category||'',r.icon||'',r.customMediaId||null,JSON.stringify(r.tags||[]),r.activeFrom||'',r.activeTo||'',r.layerId||null,r.factionId||null,JSON.stringify(r.bookIds||[]),r.storyRelevance||'',r.active===false?0:1,r.createdAt||now(),r.updatedAt||now());
  if(store==='workspace') return env.DB.prepare(`INSERT INTO workspace (id,kind,title,data_json,created_at,updated_at) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,title=excluded.title,data_json=excluded.data_json,updated_at=excluded.updated_at`).bind(r.id,r.kind,r.title||'',JSON.stringify(r.data||{}),r.createdAt||now(),r.updatedAt||now());
  throw new Error(`Unsupported store ${store}`);
}

export async function readStore(env,store,{includeRevisions=false}={}){
  const sql=store==='workspace'&&!includeRevisions?`SELECT * FROM workspace WHERE kind <> 'revision'`:`SELECT * FROM ${TABLE[store]}`;
  const result=await env.DB.prepare(sql).all();
  return (result.results||[]).map(row=>rowToRecord(store,row));
}

export async function readRecord(env,store,key){
  const keyCol=store==='settings'?'key':'id';
  const row=await env.DB.prepare(`SELECT * FROM ${TABLE[store]} WHERE ${keyCol}=?`).bind(key).first();
  if(store==='workspace'&&row?.kind==='revision') return null;
  return rowToRecord(store,row);
}
