import { KNOWLEDGE_STATES, createEmptyEntity } from '../domain/schema.js';
import { storyPath, compareStoryRefs } from '../domain/story.js';
import { compareTimelineEvents, eventRangeLabel } from '../domain/timeline.js';
import { knowledgeAtPoint, knowledgeAsymmetryAtPoint, readerKnowledgeAtPoint, readerKnowledgeTimeline, mysteryProgression, mysteryAnalysis, continuityWarnings, backlinksFor, sceneContinuity, plotCoverage, characterInteractionMatrix, locationUsage, crossLinkSuggestions, contentTree, diplomacyEdges } from '../domain/intelligence.js';
import { putOne, deleteOne, getEntityRevisions } from '../data/db.js';
import { downloadBlob } from '../data/backup.js';

const PROMPTS={
  character:['Where were they born?','What do they falsely believe?','Who do they trust most?','What secret are they keeping?','What do they want at the start versus the end?'],
  location:['Who controls this place?','What does the population believe about its history?','What changed here most recently?','What would a visitor misunderstand?'],
  organization:['How is leadership chosen?','Who actually holds power?','Who opposes this group?','What resource keeps it influential?'],
  civilization:['Who actually holds power?','What does this society fear losing?','What does it misunderstand about its own history?'],
  religion:['Who benefits from the accepted interpretation?','What schisms exist?','What is true that believers do not know?'],
  event:['What had to happen before this?','Who remembers it incorrectly?','What later events depend on it?'],
  mystery:['What is the earliest fair clue?','What false interpretation should feel plausible?','What changes after the truth is known?']
};

export function createV3Controller(ctx){
  const {state,main,esc,text,id,now,entityById,activeEntities,entityLink,typeLabel,setRoute,renderRoute,refreshState,toast,projectSetting,openEntryEditor}=ctx;
  const ws=(kind)=>state.workspace.filter(w=>!kind||w.kind===kind);
  const revisionCache=new Map();
  const option=(e,selected='')=>`<option value="${esc(e.id)}" ${e.id===selected?'selected':''}>${esc(e.name)} — ${esc(typeLabel(e.type))}</option>`;
  const storyEntities=()=>activeEntities().filter(e=>['book','chapter','scene'].includes(e.type)).sort((a,b)=>compareStoryRefs(a.id,b.id,state.entities));
  const data=()=>({entities:state.entities,relations:state.relations,media:state.media,clues:state.clues,reveals:state.reveals,knowledge:state.knowledge,mapVersions:state.mapVersions,mapMarkers:state.mapMarkers,workspace:state.workspace});
  const workspaceRecord=(kind,title,dataValue,existing=null)=>({id:existing?.id||id(),kind,title:title||existing?.title||'',data:dataValue||{},createdAt:existing?.createdAt||now(),updatedAt:now()});

  function renderContinuity(){
    const characters=activeEntities().filter(e=>e.type==='character').sort((a,b)=>a.name.localeCompare(b.name));
    const points=storyEntities();
    const books=activeEntities().filter(e=>e.type==='book').sort((a,b)=>compareStoryRefs(a.id,b.id,state.entities));
    const locations=activeEntities().filter(e=>e.type==='location').sort((a,b)=>a.name.localeCompare(b.name));
    const mysteries=activeEntities().filter(e=>e.type==='mystery').sort((a,b)=>a.name.localeCompare(b.name));
    const scenes=activeEntities().filter(e=>e.type==='scene').sort((a,b)=>compareStoryRefs(a.id,b.id,state.entities));
    const warnings=continuityWarnings(data());
    main.innerHTML=ctx.pageHeader('Continuity','Inspect what characters know, what readers know, mystery progression, dependencies, and deterministic continuity warnings.','')+`
      <div class="grid stats"><div class="card"><div class="muted small">Warnings</div><div class="stat-value">${warnings.length}</div></div><div class="card"><div class="muted small">Knowledge records</div><div class="stat-value">${state.knowledge.length}</div></div><div class="card"><div class="muted small">Clues</div><div class="stat-value">${state.clues.length}</div></div><div class="card"><div class="muted small">Reveals</div><div class="stat-value">${state.reveals.length}</div></div></div>
      <div class="grid two section">
        <section class="card"><h2>Character knowledge at a story point</h2><div class="form-grid section"><label>Character<select id="continuity-character"><option value="">Choose…</option>${characters.map(option).join('')}</select></label><label>Book / chapter / scene<select id="continuity-point"><option value="">Choose…</option>${points.map(option).join('')}</select></label></div><div id="continuity-character-results" class="section"></div></section>
        <section class="card"><h2>Reader knowledge by a story point</h2><div class="form-grid section"><label>Book / chapter / scene<select id="reader-point"><option value="">Choose…</option>${points.map(option).join('')}</select></label><label>Compare with character<select id="reader-compare-character"><option value="">No comparison</option>${characters.map(option).join('')}</select></label></div><div id="reader-point-results" class="section"></div></section>
      </div>
      <div class="grid two section"><section class="card"><h2>Mystery / clue / reveal progression</h2><div class="form-grid section"><label>Mystery<select id="continuity-mystery"><option value="">Choose…</option>${mysteries.map(option).join('')}</select></label><label>Status<select id="mystery-state-filter"><option value="">Any</option><option value="unresolved">Unresolved</option><option value="resolved">Resolved</option></select></label><label>Book<select id="mystery-book-filter"><option value="">Any</option>${books.map(option).join('')}</select></label><label>Chapter / scene<select id="mystery-point-filter"><option value="">Any</option>${points.filter(e=>e.type!=='book').map(option).join('')}</select></label><label>Character<select id="mystery-character-filter"><option value="">Any</option>${characters.map(option).join('')}</select></label><label>Location<select id="mystery-location-filter"><option value="">Any</option>${locations.map(option).join('')}</select></label></div><div id="continuity-mystery-results" class="section"></div></section><section class="card"><h2>Scene continuity dashboard</h2><label class="section">Scene<select id="continuity-scene"><option value="">Choose…</option>${scenes.map(option).join('')}</select></label><div id="continuity-scene-results" class="section"></div></section></div>
      <section class="card section"><div class="section-title"><div><h2>Canon contradiction checks</h2><div class="muted small">These are possible problems, not automatic corrections. Sortable dates enable stronger checks for births, deaths, locations, and event dependencies.</div></div></div><div class="tracking-list">${warnings.length?warnings.map(w=>warningRow(w)).join(''):'<div class="muted small">No deterministic warnings found.</div>'}</div></section>
      <section class="card section"><h2>Dependency / impact lookup</h2><label class="section">Entry<select id="impact-entry"><option value="">Choose…</option>${activeEntities().sort((a,b)=>a.name.localeCompare(b.name)).map(option).join('')}</select></label><div id="impact-results" class="section"></div></section>`;

    const updateCharacter=()=>{
      const c=document.querySelector('#continuity-character')?.value,p=document.querySelector('#continuity-point')?.value,out=document.querySelector('#continuity-character-results'); if(!out)return;
      if(!c||!p){out.innerHTML='<div class="muted small">Choose a character and story point.</div>';return;}
      const result=knowledgeAtPoint({knowledge:state.knowledge,entities:state.entities,characterId:c,pointId:p});
      const gap=knowledgeAsymmetryAtPoint({knowledge:state.knowledge,reveals:state.reveals,entities:state.entities,characterId:c,pointId:p});
      out.innerHTML=`${result.rows.length?`<div class="tracking-list">${result.rows.map(k=>`<div class="tracking-row"><div><strong>${esc(entityById(k.subjectEntityId)?.name||'Missing subject')}</strong><div class="list-meta">${esc(k.state)}${k.storyEntityId?` • ${esc(storyPath(entityById(k.storyEntityId),state.entities))}`:''}</div><div class="small">${esc(k.belief||'')}</div></div></div>`).join('')}</div>`:'<div class="muted small">No knowledge state has been recorded by this point.</div>'}<div class="detail-section"><h3>Knowledge asymmetry</h3><div class="continuity-grid"><div><span class="muted small">Character knows / reader does not</span><strong>${gap.characterKnowsReaderDoesNot.length}</strong></div><div><span class="muted small">Reader knows / character does not</span><strong>${gap.readerKnowsCharacterDoesNot.length}</strong></div><div><span class="muted small">False / rejected beliefs</span><strong>${gap.falseBeliefs.length}</strong></div></div>${gap.characterKnowsReaderDoesNot.length?`<div class="small section"><b>Character-only:</b> ${gap.characterKnowsReaderDoesNot.map(k=>esc(entityById(k.subjectEntityId)?.name||'Unknown')).join(' • ')}</div>`:''}${gap.readerKnowsCharacterDoesNot.length?`<div class="small"><b>Reader-only:</b> ${gap.readerKnowsCharacterDoesNot.map(id=>esc(entityById(id)?.name||'Unknown')).join(' • ')}</div>`:''}</div>`;
    };
    const updateReader=()=>{
      const p=document.querySelector('#reader-point')?.value,c=document.querySelector('#reader-compare-character')?.value,out=document.querySelector('#reader-point-results'); if(!out)return;
      if(!p){out.innerHTML='<div class="muted small">Choose a story point.</div>';return;}
      const result=readerKnowledgeAtPoint({knowledge:state.knowledge,reveals:state.reveals,entities:state.entities,pointId:p});
      const timeline=readerKnowledgeTimeline({knowledge:state.knowledge,reveals:state.reveals,clues:state.clues,entities:state.entities}).filter(r=>!r.storyId||compareStoryRefs(r.storyId,p,state.entities)<=0);
      const gap=c?knowledgeAsymmetryAtPoint({knowledge:state.knowledge,reveals:state.reveals,entities:state.entities,characterId:c,pointId:p}):null;
      out.innerHTML=`<div class="tracking-list">${timeline.length?timeline.map(r=>`<div class="tracking-row"><div><strong>${esc(r.title)}</strong><div class="list-meta">${esc(r.kind)}${r.storyId?` • ${esc(storyPath(entityById(r.storyId),state.entities))}`:''}</div></div></div>`).join(''):'<div class="muted small">The reader has no structured knowledge by this point.</div>'}</div><div class="muted small section">${result.reveals.length} reveal${result.reveals.length===1?'':'s'} and ${result.direct.length} explicit reader knowledge record${result.direct.length===1?'':'s'} apply.</div>${gap?`<div class="detail-section"><h3>Compared with ${esc(entityById(c)?.name||'character')}</h3><div class="small"><b>Reader knows but character does not:</b> ${gap.readerKnowsCharacterDoesNot.map(id=>esc(entityById(id)?.name||'Unknown')).join(' • ')||'None structured'}</div><div class="small section"><b>Character knows but reader does not:</b> ${gap.characterKnowsReaderDoesNot.map(k=>esc(entityById(k.subjectEntityId)?.name||'Unknown')).join(' • ')||'None structured'}</div></div>`:''}`;
    };
    const storyContains=(rowId,filterId)=>{
      if(!filterId)return true; if(!rowId)return false; if(rowId===filterId)return true;
      const row=entityById(rowId),filter=entityById(filterId); if(!row||!filter)return false;
      if(filter.type==='book'){ if(row.type==='chapter')return row.fields?.parentBookId===filter.id; if(row.type==='scene'){const chapter=entityById(row.fields?.parentChapterId);return chapter?.fields?.parentBookId===filter.id;} }
      if(filter.type==='chapter'&&row.type==='scene')return row.fields?.parentChapterId===filter.id;
      return false;
    };
    const storySceneIdsForRow=(rowId)=>{const row=entityById(rowId);if(!row)return[];if(row.type==='scene')return[row.id];if(row.type==='chapter')return activeEntities().filter(e=>e.type==='scene'&&e.fields?.parentChapterId===row.id).map(e=>e.id);if(row.type==='book'){const chapterIds=new Set(activeEntities().filter(e=>e.type==='chapter'&&e.fields?.parentBookId===row.id).map(e=>e.id));return activeEntities().filter(e=>e.type==='scene'&&chapterIds.has(e.fields?.parentChapterId)).map(e=>e.id);}return[];};
    const updateMystery=()=>{
      const m=document.querySelector('#continuity-mystery')?.value,out=document.querySelector('#continuity-mystery-results'); if(!out)return;
      if(!m){out.innerHTML='<div class="muted small">Choose a mystery.</div>';return;}
      const result=mysteryAnalysis(m,{clues:state.clues,reveals:state.reveals,entities:state.entities});
      const stateFilter=document.querySelector('#mystery-state-filter')?.value||'',book=document.querySelector('#mystery-book-filter')?.value||'',point=document.querySelector('#mystery-point-filter')?.value||'',character=document.querySelector('#mystery-character-filter')?.value||'',location=document.querySelector('#mystery-location-filter')?.value||'';
      if((stateFilter==='resolved'&&!result.hasReveal)||(stateFilter==='unresolved'&&result.hasReveal)){out.innerHTML='<div class="muted small">This mystery does not match the selected resolved/unresolved filter.</div>';return;}
      let rows=result.rows.filter(row=>storyContains(row.storyId,book)&&storyContains(row.storyId,point));
      if(character) rows=rows.filter(row=>storySceneIdsForRow(row.storyId).some(sceneId=>state.relations.some(rel=>rel.type==='appears_in'&&((rel.fromId===character&&rel.toId===sceneId)||(rel.toId===character&&rel.fromId===sceneId)))));
      if(location) rows=rows.filter(row=>storySceneIdsForRow(row.storyId).some(sceneId=>entityById(sceneId)?.fields?.locationId===location));
      out.innerHTML=`<div class="continuity-grid"><div><span class="muted small">Clues</span><strong>${result.clueCount}</strong></div><div><span class="muted small">Reveals</span><strong>${result.revealCount}</strong></div><div><span class="muted small">Setup before first reveal</span><strong>${result.cluesBeforeReveal.length}</strong></div><div><span class="muted small">State</span><strong>${result.hasReveal?'Resolved':'Unresolved'}</strong></div></div>${result.insufficientSetup?'<div class="badge contradicted section">First reveal has no scheduled setup clue</div>':''}${rows.length?`<div class="reveal-board section">${rows.map(r=>`<div class="reveal-node"><div class="reveal-kind">${esc(r.kind)}</div><strong>${esc(r.title)}</strong><div class="muted small">${esc(r.storyId?storyPath(entityById(r.storyId),state.entities):'Unscheduled')}</div>${r.record?.mysteryIds?.length?`<div class="small">Also supports ${r.record.mysteryIds.map(id=>esc(entityById(id)?.name||'Missing')).join(' • ')}</div>`:''}</div>`).join('')}</div>`:'<div class="muted small section">No progression rows match these filters.</div>'}`;
    };
    const updateScene=()=>{ const s=document.querySelector('#continuity-scene')?.value,out=document.querySelector('#continuity-scene-results'); if(!out)return; const info=s?sceneContinuity(s,data()):null; out.innerHTML=info?sceneDashboardHtml(info):'<div class="muted small">Choose a scene.</div>'; };
    const updateImpact=()=>{ const target=document.querySelector('#impact-entry')?.value,out=document.querySelector('#impact-results'); if(!out)return; if(!target){out.innerHTML='<div class="muted small">Choose an entry.</div>';return;} const refs=backlinksFor(target,data()); out.innerHTML=refs.length?`<div class="tracking-list">${refs.map(ref=>impactRow(ref)).join('')}</div>`:'<div class="muted small">No structured dependencies found.</div>'; };
    for(const [sel,fn] of [['#continuity-character',updateCharacter],['#continuity-point',updateCharacter],['#reader-point',updateReader],['#reader-compare-character',updateReader],['#continuity-mystery',updateMystery],['#mystery-state-filter',updateMystery],['#mystery-book-filter',updateMystery],['#mystery-point-filter',updateMystery],['#mystery-character-filter',updateMystery],['#mystery-location-filter',updateMystery],['#continuity-scene',updateScene],['#impact-entry',updateImpact]]) document.querySelector(sel)?.addEventListener('input',fn);
  }

  function warningRow(w){ const e=entityById(w.entityId); return `<div class="tracking-row warning-${esc(w.severity||'warning')}"><div><strong>${esc(w.message)}</strong><div class="list-meta">${esc(w.code||'continuity')}${e?` • ${esc(e.name)}`:''}</div></div>${e?`<button class="button ghost" data-open-entry="${esc(e.id)}" data-open-route="${esc(ctx.sectionForType(e.type))}">Open</button>`:''}</div>`; }
  function impactRow(ref){ const source=entityById(ref.sourceId); return `<div class="tracking-row"><div><strong>${esc(ref.kind)}</strong><div class="list-meta">${esc(source?.name||ref.record?.title||ref.record?.label||ref.id)}</div></div>${source?`<button class="button ghost" data-open-entry="${esc(source.id)}" data-open-route="${esc(ctx.sectionForType(source.type))}">Open</button>`:''}</div>`; }
  function sceneDashboardHtml(info){
    const knowledgeRows=info.characters.flatMap(c=>(info.knowledge?.[c.id]||[]).map(k=>({character:c,row:k})));
    return `<div class="continuity-grid"><div><span class="muted small">Location</span><strong>${esc(info.location?.name||info.scene.fields?.locationText||'Unspecified')}</strong></div><div><span class="muted small">Characters</span><strong>${info.characters.length}</strong></div><div><span class="muted small">Clues / reveals</span><strong>${info.clues.length} / ${info.reveals.length}</strong></div><div><span class="muted small">Active mysteries</span><strong>${info.activeMysteries?.length||0}</strong></div><div><span class="muted small">Plot beats</span><strong>${info.beats.length}</strong></div><div><span class="muted small">Timeline position</span><strong>${esc(info.timelinePosition?.storyDate||info.timelinePosition?.path||'Story order only')}</strong></div></div>
      ${info.timelinePosition?.path?`<div class="muted small section">${esc(info.timelinePosition.path)}${info.timelinePosition.storyDateSort!==''?` • sortable date ${esc(info.timelinePosition.storyDateSort)}`:''}</div>`:''}
      ${info.characters.length?`<div class="detail-section"><h3>Characters present</h3>${info.characters.map(c=>entityLink(c,'characters')).join(' • ')}</div>`:''}
      ${knowledgeRows.length?`<div class="detail-section"><h3>Character knowledge at this scene</h3><div class="tracking-list">${knowledgeRows.slice(0,24).map(({character,row})=>`<div class="tracking-row"><div><strong>${esc(character.name)} — ${esc(entityById(row.subjectEntityId)?.name||'Unknown subject')}</strong><div class="list-meta">${esc(row.state)}</div><div class="small">${esc(row.belief||'')}</div></div></div>`).join('')}</div></div>`:''}
      ${info.activeMysteries?.length?`<div class="detail-section"><h3>Active mysteries</h3><div class="actions">${info.activeMysteries.map(m=>`<span class="badge">${esc(m.name)}</span>`).join('')}</div></div>`:''}
      ${info.clues.length||info.reveals.length?`<div class="detail-section"><h3>Clues / reveals in this scene</h3><div class="tracking-list">${info.clues.map(c=>`<div class="tracking-row"><div><strong>${esc(c.label||'Clue')}</strong><div class="list-meta">${esc(c.kind||'Clue')}</div></div></div>`).join('')}${info.reveals.map(r=>`<div class="tracking-row"><div><strong>${esc(r.title||'Reveal')}</strong><div class="list-meta">Reveal</div></div></div>`).join('')}</div></div>`:''}
      ${info.beats.length?`<div class="detail-section"><h3>Plot threads</h3><div class="tracking-list">${info.beats.map(b=>`<div class="tracking-row"><div><strong>${esc(ws('plotThread').find(t=>t.id===b.data?.threadId)?.title||'Thread')}</strong><div class="small">${esc(b.title)}</div></div></div>`).join('')}</div></div>`:''}
      ${info.characters.some(c=>(info.asymmetry?.[c.id]?.readerKnowsCharacterDoesNot||[]).length||(info.asymmetry?.[c.id]?.characterKnowsReaderDoesNot||[]).length)?`<div class="detail-section"><h3>Reader / character information gaps</h3>${info.characters.map(c=>{const g=info.asymmetry?.[c.id];if(!g)return'';return `<div class="small section"><b>${esc(c.name)}:</b> reader-only ${g.readerKnowsCharacterDoesNot.length}; character-only ${g.characterKnowsReaderDoesNot.length}; false/rejected ${g.falseBeliefs.length}</div>`;}).join('')}</div>`:''}
      ${info.warnings.length?`<div class="detail-section"><h3>Continuity warnings</h3>${info.warnings.map(warningRow).join('')}</div>`:''}`;
  }


  function renderPlotGrid(){
    const threads=ws('plotThread').sort((a,b)=>(Number(a.data?.order)||0)-(Number(b.data?.order)||0)||a.title.localeCompare(b.title));
    const scenes=activeEntities().filter(e=>e.type==='scene').sort((a,b)=>compareStoryRefs(a.id,b.id,state.entities));
    const books=activeEntities().filter(e=>e.type==='book').sort((a,b)=>(Number(a.fields?.order)||999)-(Number(b.fields?.order)||999));
    const chars=activeEntities().filter(e=>e.type==='character').sort((a,b)=>a.name.localeCompare(b.name));
    const series=activeEntities().find(e=>e.type==='trilogy')||null; const compass=series?.fields||projectSetting().storyCompass||{};
    main.innerHTML=ctx.pageHeader('Plot Grid','Plan the middle without losing the fixed points you already know. Plot beats reference the same scenes, mysteries, reveals, characters, events, and locations used everywhere else.','')+`
      <section class="card story-compass"><div class="section-title"><div><h2>Story Compass</h2><div class="muted small">Optional anchors for the parts you know before you discover the path between them.</div></div></div><form id="story-compass-form" class="form-grid"><label class="full">Beginning / starting state<textarea id="compass-beginning" rows="3">${esc(compass.startingState||compass.beginning||'')}</textarea></label><label class="full">Primary protagonists<select id="compass-protagonists" multiple size="${Math.min(6,Math.max(3,chars.length))}">${chars.map(c=>`<option value="${esc(c.id)}" ${(compass.protagonistIds||[]).includes(c.id)?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>End goal / destination<textarea id="compass-goal" rows="3">${esc(compass.endGoal||'')}</textarea></label><label>Central prize / truth / answer<textarea id="compass-prize" rows="3">${esc(compass.centralPrizeTruth||'')}</textarea></label><label class="full">Non-negotiable truths<textarea id="compass-truths" rows="3">${esc(compass.nonNegotiableTruths||'')}</textarea></label><label class="full">Intended ending / final state<textarea id="compass-ending" rows="3">${esc(compass.intendedEnding||'')}</textarea></label><div class="full"><button class="button primary" type="submit">Save Story Compass</button></div></form></section>
      <section class="card section"><div class="section-title"><div><h2>Plot threads</h2><div class="muted small">Columns in the grid. Threads can be broad or extremely specific.</div></div></div><form id="plot-thread-form" class="quick-capture"><input id="plot-thread-name" placeholder="Main Plot, Romance, Villain Plan…" required/><button class="button primary" type="submit">Add thread</button></form>${threads.length?`<div class="actions section">${threads.map(t=>`<span class="badge">${esc(t.title)} <button class="tiny-x" data-delete-workspace="${esc(t.id)}" aria-label="Delete ${esc(t.title)}">×</button></span>`).join('')}</div>`:''}</section>
      <section class="card section"><div class="section-title"><div><h2>Story / Plot Grid</h2><div class="muted small">Drag beats between cells. Scene rows remain the canonical story structure.</div></div></div>${threads.length&&scenes.length?plotGridHtml(scenes,threads):'<div class="empty-state"><strong>Grid needs scenes and plot threads</strong><div>Create Scene entries and at least one thread.</div></div>'}</section>
      <div class="grid two section"><section class="card"><h2>Plot-thread coverage</h2><label class="section">Thread<select id="coverage-thread"><option value="">Choose…</option>${threads.map(t=>`<option value="${esc(t.id)}">${esc(t.title)}</option>`).join('')}</select></label><div id="coverage-results" class="section"></div></section><section class="card"><h2>Story organizer</h2><label class="section">Book<select id="organizer-book"><option value="">Choose…</option>${books.map(option).join('')}</select></label><div id="organizer-results" class="section"></div></section></div>
      <section class="card section"><div class="section-title"><div><h2>Series overview</h2><div class="muted small">Books, unresolved mysteries, major reveals, and the arc above individual books.</div></div></div>${seriesOverviewHtml(books)}</section>
      <section class="card section"><h2>Character presence / interaction matrix</h2><div class="muted small">Counts are derived from appears_in relationships between Characters and Scenes.</div><div class="section interaction-scroll">${interactionMatrixHtml()}</div></section>`;
    document.querySelector('#story-compass-form')?.addEventListener('submit',saveStoryCompass);
    document.querySelector('#plot-thread-form')?.addEventListener('submit',savePlotThread);
    document.querySelector('#coverage-thread')?.addEventListener('input',e=>{ const out=document.querySelector('#coverage-results'); const rows=plotCoverage({entities:state.entities,workspace:state.workspace},e.target.value); out.innerHTML=e.target.value?`<div class="coverage-list">${rows.map(r=>`<div class="coverage-row"><span>${esc(storyPath(r.scene,state.entities))}</span><b>${r.covered?'✓':'—'}</b></div>`).join('')}</div>`:'<div class="muted small">Choose a thread.</div>'; });
    document.querySelector('#organizer-book')?.addEventListener('input',e=>renderOrganizer(e.target.value));
    bindPlotDnD();
  }

  function plotGridHtml(scenes,threads){
    return `<div class="plot-grid-scroll"><div class="plot-grid" style="--plot-cols:${threads.length}"><div class="plot-grid-corner">Scene</div>${threads.map(t=>`<div class="plot-grid-head">${esc(t.title)}</div>`).join('')}${scenes.map(scene=>`<div class="plot-grid-scene"><button class="inline-link" data-open-entry="${esc(scene.id)}" data-open-route="story">${esc(storyPath(scene,state.entities))}</button></div>${threads.map(thread=>{const beats=ws('plotBeat').filter(b=>b.data?.sceneId===scene.id&&b.data?.threadId===thread.id);return `<div class="plot-cell" data-drop-scene="${esc(scene.id)}" data-drop-thread="${esc(thread.id)}">${beats.map(b=>{const linked=b.data?.linkedEntityId?entityById(b.data.linkedEntityId):null,clue=b.data?.clueId?state.clues.find(c=>c.id===b.data.clueId):null,reveal=b.data?.revealId?state.reveals.find(r=>r.id===b.data.revealId):null,linkedLabel=linked?.name||clue?.label||reveal?.title||'';return `<article class="plot-beat" draggable="true" data-drag-beat="${esc(b.id)}"><span>${esc(b.title)}${linkedLabel?`<small>${esc(linkedLabel)}</small>`:''}</span><button class="tiny-x" data-delete-workspace="${esc(b.id)}" aria-label="Delete beat">×</button></article>`;}).join('')}<button class="plot-add" data-add-plot-beat="1" data-scene-id="${esc(scene.id)}" data-thread-id="${esc(thread.id)}" aria-label="Add plot beat">+</button></div>`;}).join('')}`).join('')}</div></div>`;
  }
  async function saveStoryCompass(event){ event.preventDefault(); const existing=activeEntities().find(e=>e.type==='trilogy')||null, overview=existing?structuredClone(existing):createEmptyEntity('trilogy'); if(!existing){overview.name='Series Overview';overview.summary='High-level anchors for the series.';} overview.fields={...overview.fields,startingState:document.querySelector('#compass-beginning').value.trim(),protagonistIds:[...document.querySelector('#compass-protagonists').selectedOptions].map(o=>o.value),endGoal:document.querySelector('#compass-goal').value.trim(),centralPrizeTruth:document.querySelector('#compass-prize').value.trim(),nonNegotiableTruths:document.querySelector('#compass-truths').value.trim(),intendedEnding:document.querySelector('#compass-ending').value.trim()}; overview.updatedAt=now(); await putOne('entities',overview,existing?{baseUpdatedAt:existing.updatedAt}:{}); const project=structuredClone(projectSetting()); if(project.storyCompass) delete project.storyCompass; await putOne('settings',{key:'project',value:project}); await refreshState(); renderPlotGrid(); toast('Series Story Compass saved.'); }
  async function savePlotThread(event){ event.preventDefault(); const input=document.querySelector('#plot-thread-name'),title=input.value.trim(); if(!title)return; await putOne('workspace',workspaceRecord('plotThread',title,{order:ws('plotThread').length+1})); await refreshState(); renderPlotGrid(); toast('Plot thread added.'); }
  async function addPlotBeat(sceneId,threadId){ const title=prompt('Plot beat'); if(!title?.trim())return; const linkName=(prompt('Optional: exact name/title of an Entry, Clue, or Reveal to link')||'').trim(); const linked=linkName?activeEntities().find(e=>e.name.toLowerCase()===linkName.toLowerCase()):null; const clue=!linked&&linkName?state.clues.find(c=>(c.label||'').toLowerCase()===linkName.toLowerCase()):null; const reveal=!linked&&!clue&&linkName?state.reveals.find(r=>(r.title||'').toLowerCase()===linkName.toLowerCase()):null; await putOne('workspace',workspaceRecord('plotBeat',title.trim(),{sceneId,threadId,linkedEntityId:linked?.id||null,clueId:clue?.id||null,revealId:reveal?.id||null,order:ws('plotBeat').filter(b=>b.data?.sceneId===sceneId&&b.data?.threadId===threadId).length+1})); await refreshState(); renderPlotGrid(); }
  function bindPlotDnD(){
    document.querySelectorAll('[data-drag-beat]').forEach(el=>el.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',el.dataset.dragBeat)));
    document.querySelectorAll('.plot-cell').forEach(cell=>{cell.addEventListener('dragover',e=>{e.preventDefault();cell.classList.add('drag-over');});cell.addEventListener('dragleave',()=>cell.classList.remove('drag-over'));cell.addEventListener('drop',async e=>{e.preventDefault();cell.classList.remove('drag-over');const beat=state.workspace.find(w=>w.id===e.dataTransfer.getData('text/plain'));if(!beat)return;await putOne('workspace',{...beat,data:{...beat.data,sceneId:cell.dataset.dropScene,threadId:cell.dataset.dropThread},updatedAt:now()});await refreshState();renderPlotGrid();});});
  }
  function renderOrganizer(bookId){
    const out=document.querySelector('#organizer-results'); if(!out)return;
    if(!bookId){out.innerHTML='<div class="muted small">Choose a book.</div>';return;}
    const chapters=activeEntities().filter(e=>e.type==='chapter'&&e.fields?.parentBookId===bookId).sort((a,b)=>(Number(a.fields?.number)||999)-(Number(b.fields?.number)||999));
    out.innerHTML=chapters.length?`<div class="reorder-list">${chapters.map(c=>{const scenes=activeEntities().filter(e=>e.type==='scene'&&e.fields?.parentChapterId===c.id).sort((a,b)=>(Number(a.fields?.order)||999)-(Number(b.fields?.order)||999));return `<div class="reorder-chapter"><div class="reorder-item" draggable="true" data-drag-chapter="${esc(c.id)}"><span>↕</span><strong>${esc(c.name)}</strong><span class="muted small">Chapter ${esc(c.fields?.number||'')}</span></div>${scenes.length?`<div class="reorder-scenes" data-scene-chapter="${esc(c.id)}">${scenes.map(scene=>`<div class="reorder-scene" draggable="true" data-drag-scene="${esc(scene.id)}"><span>↕</span><button class="inline-link" data-open-entry="${esc(scene.id)}" data-open-route="story">${esc(scene.name)}</button><span class="muted small">${esc(scene.fields?.order||'')}</span></div>`).join('')}</div>`:'<div class="muted small reorder-scenes">No scenes.</div>'}</div>`;}).join('')}</div><div class="muted small section">Drag chapters to change chapter numbers. Drag scenes inside a chapter to change scene order. This changes planning order only; it never rewrites historical canon records.</div>`:'<div class="muted small">No chapters in this book.</div>';
    let draggedChapter=null,draggedScene=null;
    document.querySelectorAll('[data-drag-chapter]').forEach(el=>{el.addEventListener('dragstart',e=>{draggedChapter=el.dataset.dragChapter;draggedScene=null;e.dataTransfer?.setData('text/chapter',draggedChapter);});el.addEventListener('dragover',e=>{if(draggedChapter)e.preventDefault();});el.addEventListener('drop',async e=>{if(!draggedChapter)return;e.preventDefault();const target=el.dataset.dragChapter;if(draggedChapter===target)return;const order=chapters.map(c=>c.id).filter(x=>x!==draggedChapter);order.splice(order.indexOf(target),0,draggedChapter);for(let i=0;i<order.length;i++){const c=entityById(order[i]);if(Number(c.fields?.number)!==i+1)await putOne('entities',{...c,fields:{...c.fields,number:i+1},updatedAt:now()},{baseUpdatedAt:c.updatedAt});}await refreshState();renderOrganizer(bookId);toast('Chapter order updated.');});});
    document.querySelectorAll('[data-drag-scene]').forEach(el=>{el.addEventListener('dragstart',e=>{draggedScene=el.dataset.dragScene;draggedChapter=null;e.stopPropagation();e.dataTransfer?.setData('text/scene',draggedScene);});el.addEventListener('dragover',e=>{if(draggedScene)e.preventDefault();});el.addEventListener('drop',async e=>{if(!draggedScene)return;e.preventDefault();e.stopPropagation();const target=el.dataset.dragScene,source=entityById(draggedScene),targetScene=entityById(target);if(!source||!targetScene||source.id===targetScene.id||source.fields?.parentChapterId!==targetScene.fields?.parentChapterId)return toast('Scenes can be reordered within their current chapter.');const chapterId=source.fields.parentChapterId;const ordered=activeEntities().filter(x=>x.type==='scene'&&x.fields?.parentChapterId===chapterId).sort((a,b)=>(Number(a.fields?.order)||999)-(Number(b.fields?.order)||999)).map(x=>x.id).filter(x=>x!==source.id);ordered.splice(ordered.indexOf(targetScene.id),0,source.id);for(let i=0;i<ordered.length;i++){const scene=entityById(ordered[i]);if(Number(scene.fields?.order)!==i+1)await putOne('entities',{...scene,fields:{...scene.fields,order:i+1},updatedAt:now()},{baseUpdatedAt:scene.updatedAt});}await refreshState();renderOrganizer(bookId);toast('Scene order updated.');});});
  }

  function seriesOverviewHtml(books){ const mysteries=activeEntities().filter(e=>e.type==='mystery'),open=mysteries.filter(m=>!state.reveals.some(r=>r.mysteryId===m.id)); return `<div class="grid stats"><div><div class="muted small">Books</div><strong>${books.length}</strong></div><div><div class="muted small">Mysteries</div><strong>${mysteries.length}</strong></div><div><div class="muted small">Still unresolved</div><strong>${open.length}</strong></div><div><div class="muted small">Major reveals</div><strong>${state.reveals.length}</strong></div></div>${books.length?`<div class="tracking-list section">${books.map(b=>`<div class="tracking-row"><div>${entityLink(b,'story')}<div class="list-meta">${esc(b.fields?.premise||b.summary||'No premise yet.')}</div></div></div>`).join('')}</div>`:''}`; }
  function interactionMatrixHtml(){ const matrix=characterInteractionMatrix(data()),chars=matrix.characters.slice(0,20); if(!chars.length)return '<div class="muted small">Add Characters and appears_in relationships to build the matrix.</div>'; return `<table class="matrix"><thead><tr><th>Character</th>${chars.map(c=>`<th title="${esc(c.name)}">${esc(c.name.slice(0,8))}</th>`).join('')}</tr></thead><tbody>${chars.map(a=>`<tr><th>${esc(a.name)}</th>${chars.map(b=>{if(a.id===b.id)return '<td>—</td>';const key=[a.id,b.id].sort().join('|');return `<td>${matrix.counts.get(key)||0}</td>`;}).join('')}</tr>`).join('')}</tbody></table>`; }

  function renderWorldTools(){
    const locations=activeEntities().filter(e=>e.type==='location').sort((a,b)=>a.name.localeCompare(b.name)); const events=activeEntities().filter(e=>e.type==='event').sort(compareTimelineEvents); const entities=activeEntities().filter(e=>!['idea','question'].includes(e.type)).sort((a,b)=>a.name.localeCompare(b.name)); const calendars=ws('calendar');
    main.innerHTML=ctx.pageHeader('World Tools','Cross-reference geography, history, politics, hierarchies, and custom timekeeping without creating duplicate lore.','')+`
      <div class="grid two"><section class="card"><h2>Map + Timeline</h2><label class="section">Location<select id="world-location"><option value="">Choose…</option>${locations.map(option).join('')}</select></label><div id="world-location-results" class="section"></div></section><section class="card"><h2>Parallel timelines</h2><div class="form-grid section"><label>Lane 1<select class="parallel-select"><option value="">World</option>${entities.map(option).join('')}</select></label><label>Lane 2<select class="parallel-select"><option value="">World</option>${entities.map(option).join('')}</select></label><label>Lane 3<select class="parallel-select"><option value="">None</option>${entities.map(option).join('')}</select></label></div><div id="parallel-results" class="section"></div></section></div>
      <div class="grid two section"><section class="card"><div class="section-title"><div><h2>Custom calendars</h2><div class="muted small">Optional fantasy timekeeping. Events remain normal Event records.</div></div></div><form id="calendar-form" class="form-grid"><label>Name<input id="calendar-name" required placeholder="Imperial Calendar"/></label><label>Days / week<input id="calendar-week" type="number" min="1" value="7"/></label><label class="full">Weekday names<input id="calendar-days" placeholder="Firstday, Secondday…"/></label><label class="full">Months <span class="muted small">Name:days, Name:days</span><input id="calendar-months" placeholder="Dawn:30, Ember:31"/></label><label class="full">Leap rule / seasons / moons<textarea id="calendar-notes" rows="3"></textarea></label><div class="full"><button class="button primary" type="submit">Create calendar</button></div></form>${calendars.length?`<div class="tracking-list section">${calendars.map(c=>`<div class="tracking-row"><div><strong>${esc(c.title)}</strong><div class="list-meta">${esc((c.data?.months||[]).map(m=>`${m.name} ${m.days}`).join(' • ')||'No months')}</div></div><button class="tiny-x" data-delete-workspace="${esc(c.id)}">×</button></div>`).join('')}</div>`:''}<div class="form-section"><h3>Assign a world date</h3><form id="calendar-date-form" class="form-grid"><label>Calendar<select id="calendar-date-calendar"><option value="">Choose…</option>${calendars.map(c=>`<option value="${esc(c.id)}">${esc(c.title)}</option>`).join('')}</select></label><label>Event / scene<select id="calendar-date-entity"><option value="">Choose…</option>${activeEntities().filter(e=>['event','scene'].includes(e.type)).map(option).join('')}</select></label><label>Year<input id="calendar-date-year" type="number"/></label><label>Month<input id="calendar-date-month"/></label><label>Day<input id="calendar-date-day" type="number"/></label><div><button class="button" type="submit">Assign date</button></div></form></div></section>
      <section class="card"><h2>Faction / diplomacy view</h2><div class="form-grid section"><label>Era<select id="diplomacy-era"><option value="">Any era</option>${activeEntities().filter(e=>e.type==='era').sort((a,b)=>a.name.localeCompare(b.name)).map(option).join('')}</select></label><label>Date / period search<input id="diplomacy-date" placeholder="Year 125, occupation…" /></label></div><div id="diplomacy-results" class="section"></div><div class="muted small section">Relationship records can carry an optional era and active-from / active-to range.</div></section></div>
      <div class="grid two section"><section class="card"><h2>General content tree</h2><label class="section">Root entry<select id="tree-root"><option value="">Choose…</option>${entities.map(option).join('')}</select></label><div id="tree-results" class="section"></div><div class="muted small section">Trees derive from parent_of / child_of / contains / part_of relationships.</div></section><section class="card"><h2>Location usage</h2><label class="section">Location<select id="usage-location"><option value="">Choose…</option>${locations.map(option).join('')}</select></label><div id="usage-results" class="section"></div></section></div>`;
    document.querySelector('#world-location')?.addEventListener('input',e=>renderLocationHistory(e.target.value)); document.querySelectorAll('.parallel-select').forEach(el=>el.addEventListener('input',renderParallel)); document.querySelector('#calendar-form')?.addEventListener('submit',saveCalendar); document.querySelector('#calendar-date-form')?.addEventListener('submit',saveCalendarDate); document.querySelector('#tree-root')?.addEventListener('input',e=>{const out=document.querySelector('#tree-results');out.innerHTML=e.target.value?treeHtml(contentTree(e.target.value,data())):'<div class="muted small">Choose a root.</div>';}); document.querySelector('#usage-location')?.addEventListener('input',e=>renderLocationUsage(e.target.value)); document.querySelector('#diplomacy-era')?.addEventListener('input',renderDiplomacy); document.querySelector('#diplomacy-date')?.addEventListener('input',renderDiplomacy); renderParallel(); renderDiplomacy();
  }
  function renderDiplomacy(){
    const out=document.querySelector('#diplomacy-results'); if(!out)return;
    const rows=diplomacyEdges(data(),{eraId:document.querySelector('#diplomacy-era')?.value||null,dateText:document.querySelector('#diplomacy-date')?.value||''});
    out.innerHTML=rows.length?`<div class="tracking-list">${rows.map(x=>`<div class="tracking-row"><div><strong>${esc(x.from.name)} ↔ ${esc(x.to.name)}</strong><div class="list-meta">${esc(x.relation.type.replaceAll('_',' '))}${x.relation.eraId?` • ${esc(entityById(x.relation.eraId)?.name||'Era')}`:''}${x.relation.activeFrom||x.relation.activeTo?` • ${esc([x.relation.activeFrom||'…',x.relation.activeTo||'…'].join(' → '))}`:''}${x.relation.note?` • ${esc(x.relation.note)}`:''}</div></div></div>`).join('')}</div>`:'<div class="muted small">No political relationships match. Use allied_with, hostile_to, vassal_of, trade_partner_with, occupied_by, or at_war_with relationships.</div>';
  }
  function renderLocationHistory(locationId){ const out=document.querySelector('#world-location-results');if(!out)return;if(!locationId){out.innerHTML='<div class="muted small">Choose a location.</div>';return;}const usage=locationUsage(locationId,data());const markerVersions=state.mapMarkers.filter(m=>m.locationId===locationId).map(m=>state.mapVersions.find(v=>v.id===m.mapVersionId)).filter(Boolean);out.innerHTML=`<div class="continuity-grid"><div><span class="muted small">Events</span><strong>${usage.events.length}</strong></div><div><span class="muted small">Scenes</span><strong>${usage.scenes.length}</strong></div><div><span class="muted small">Maps</span><strong>${new Set([...usage.maps.map(m=>m.id),...markerVersions.map(v=>v.mapId)]).size}</strong></div><div><span class="muted small">Child locations</span><strong>${usage.children.length}</strong></div></div>${usage.events.length?`<div class="timeline section">${usage.events.sort(compareTimelineEvents).map(e=>`<div class="timeline-item"><button class="inline-link" data-open-entry="${esc(e.id)}" data-open-route="history">${esc(eventRangeLabel(e))} — ${esc(e.name)}</button></div>`).join('')}</div>`:''}`; }
  function eventsForLane(entityId){ const all=activeEntities().filter(e=>e.type==='event').sort(compareTimelineEvents); if(!entityId)return all; const target=entityById(entityId); if(target?.type==='location')return all.filter(e=>e.fields?.locationId===entityId||state.relations.some(r=>r.type==='participated_in'&&((r.fromId===entityId&&r.toId===e.id)||(r.toId===entityId&&r.fromId===e.id)))); return all.filter(e=>state.relations.some(r=>(r.fromId===entityId&&r.toId===e.id)||(r.toId===entityId&&r.fromId===e.id))); }
  function renderParallel(){ const out=document.querySelector('#parallel-results');if(!out)return;const selects=[...document.querySelectorAll('.parallel-select')];if(!selects.length)return;out.innerHTML=`<div class="parallel-timelines">${selects.map((sel,i)=>{const entity=entityById(sel.value),events=eventsForLane(sel.value);return `<div class="parallel-lane"><strong>${esc(entity?.name||`World ${i===0?'History':'Timeline'}`)}</strong><div class="timeline section">${events.slice(0,40).map(e=>`<div class="timeline-item"><button class="inline-link" data-open-entry="${esc(e.id)}" data-open-route="history">${esc(eventRangeLabel(e))} — ${esc(e.name)}</button></div>`).join('')||'<div class="muted small">No events.</div>'}</div></div>`;}).join('')}</div>`; }
  async function saveCalendar(event){event.preventDefault();const months=document.querySelector('#calendar-months').value.split(',').map(s=>s.trim()).filter(Boolean).map(s=>{const [name,days]=s.split(':');return{name:(name||'Month').trim(),days:Number(days)||30};});await putOne('workspace',workspaceRecord('calendar',document.querySelector('#calendar-name').value.trim(),{daysPerWeek:Number(document.querySelector('#calendar-week').value)||7,weekdays:document.querySelector('#calendar-days').value.split(',').map(x=>x.trim()).filter(Boolean),months,notes:document.querySelector('#calendar-notes').value.trim()}));await refreshState();renderWorldTools();toast('Calendar created.');}
  async function saveCalendarDate(event){event.preventDefault();const calendarId=document.querySelector('#calendar-date-calendar').value,entityId=document.querySelector('#calendar-date-entity').value;if(!calendarId||!entityId)return toast('Choose a calendar and event or scene.');const title=`${entityById(entityId)?.name||'Entry'} date`;await putOne('workspace',workspaceRecord('calendarDate',title,{calendarId,entityId,year:Number(document.querySelector('#calendar-date-year').value)||0,month:document.querySelector('#calendar-date-month').value.trim(),day:Number(document.querySelector('#calendar-date-day').value)||0}));await refreshState();toast('World date assigned.');}
  function treeHtml(node,depth=0){ if(!node?.entity)return '<div class="muted small">Missing root.</div>'; return `<div class="tree-node" style="--depth:${depth}"><button class="inline-link" data-open-entry="${esc(node.entity.id)}" data-open-route="${esc(ctx.sectionForType(node.entity.type))}">${esc(node.entity.name)}</button>${node.cycle?'<span class="badge contradicted">Cycle</span>':''}</div>${(node.children||[]).map(c=>treeHtml(c,depth+1)).join('')}`; }
  function renderLocationUsage(locationId){ const out=document.querySelector('#usage-results');if(!out)return;if(!locationId){out.innerHTML='<div class="muted small">Choose a location.</div>';return;}const u=locationUsage(locationId,data());out.innerHTML=`<div class="tracking-list">${[['Scenes',u.scenes],['Events',u.events],['Characters',u.characters],['Child locations',u.children],['Maps',u.maps]].map(([label,items])=>`<div class="tracking-row"><div><strong>${esc(label)}</strong><div class="list-meta">${items.length}</div><div class="small">${items.slice(0,8).map(e=>esc(e.name)).join(' • ')||'None'}</div></div></div>`).join('')}</div>`; }

  function renderWorkbench(){
    const targets=activeEntities().sort((a,b)=>a.name.localeCompare(b.name)),notes=ws('contextNote'),tasks=ws('task'),views=ws('savedView'),scenes=activeEntities().filter(e=>e.type==='scene').sort((a,b)=>compareStoryRefs(a.id,b.id,state.entities)); const nodes=ws('whiteboardNode'),edges=ws('whiteboardEdge'); const widgets=projectSetting().dashboardWidgets||['recent','questions','mysteries','ideas','warnings'];
    main.innerHTML=ctx.pageHeader('Workbench','Scratch work that supports canon without pretending unfinished thoughts are canon. Includes notes, tasks, manuscript drafting, saved views, whiteboard, dashboard controls, and generators.','')+`
      <div class="grid two"><section class="card"><h2>Contextual notes</h2><form id="note-form" class="form-grid section"><label>Attach to<select id="note-target"><option value="">General project note</option>${targets.map(option).join('')}</select></label><label>Title<input id="note-title" required/></label><label class="full">Note<textarea id="note-body" rows="3"></textarea></label><div class="full"><button class="button primary" type="submit">Add note</button></div></form><div class="tracking-list section">${notes.length?notes.map(n=>workspaceRow(n,n.data?.resolved?'Resolved':'Open')).join(''):'<div class="muted small">No scratch notes.</div>'}</div></section>
      <section class="card"><h2>Worldbuilding tasks</h2><form id="task-form" class="form-grid section"><label>Attach to<select id="task-target"><option value="">General project task</option>${targets.map(option).join('')}</select></label><label>Task<input id="task-title" required/></label><label>Due / milestone<input id="task-due" placeholder="Book 1 revision, next pass…"/></label><div><button class="button primary" type="submit">Add task</button></div></form><div class="tracking-list section">${tasks.length?tasks.map(t=>workspaceRow(t,t.data?.done?'Done':'Open')).join(''):'<div class="muted small">No tasks.</div>'}</div></section></div>
      <div class="grid two section"><section class="card"><h2>Manuscript workspace</h2><label class="section">Scene<select id="manuscript-scene"><option value="">Choose a scene…</option>${scenes.map(option).join('')}</select></label><div id="manuscript-editor" class="section"><div class="muted small">Choose a scene to draft prose directly against its continuity record.</div></div></section><section class="card"><h2>Saved views / workspaces</h2><form id="saved-view-form" class="form-grid section"><label>Name<input id="saved-view-name" required placeholder="Book 1 Planning"/></label><label>Destination<select id="saved-view-route"><option value="story">Story</option><option value="continuity">Continuity</option><option value="plot-grid">Plot Grid</option><option value="maps">Maps</option><option value="timeline">Timeline</option><option value="world-tools">World Tools</option><option value="workbench">Workbench</option></select></label><div class="full"><button class="button primary" type="submit">Save view</button></div></form><div class="tracking-list section">${views.length?views.map(v=>`<div class="tracking-row"><button class="inline-link" data-open-saved-view="${esc(v.id)}">${esc(v.title)}</button><button class="tiny-x" data-delete-workspace="${esc(v.id)}">×</button></div>`).join(''):'<div class="muted small">No saved views yet.</div>'}</div><div class="form-section"><h3>Dashboard widgets</h3><form id="dashboard-widgets-form" class="checkbox-grid">${['recent','questions','mysteries','ideas','warnings','compass','tasks'].map(w=>`<label><input type="checkbox" value="${w}" ${widgets.includes(w)?'checked':''}/> ${esc(w[0].toUpperCase()+w.slice(1))}</label>`).join('')}<button class="button" type="submit">Save dashboard layout</button></form></div></section></div>
      <section class="card section"><div class="section-title"><div><h2>Free-form whiteboard</h2><div class="muted small">A lightweight scratch canvas. Nodes can link back to canonical entries.</div></div><button class="button" data-add-whiteboard-node="1">+ Card</button></div><div class="whiteboard" id="whiteboard">${whiteboardHtml(nodes,edges)}</div>${nodes.length>=2?`<form id="whiteboard-edge-form" class="form-grid section"><label>From<select id="edge-from">${nodes.map(n=>`<option value="${esc(n.id)}">${esc(n.title)}</option>`).join('')}</select></label><label>To<select id="edge-to">${nodes.map(n=>`<option value="${esc(n.id)}">${esc(n.title)}</option>`).join('')}</select></label><label>Label<input id="edge-label" placeholder="causes, relates to…"/></label><div><button class="button" type="submit">Connect</button></div></form>`:''}</section>
      <section class="card section"><div class="grid two"><div><h2>Random placeholder generator</h2><p class="muted small">For temporary names and brainstorming, not canon automation.</p><div class="actions"><button class="button" data-generate-name="person">Person name</button><button class="button" data-generate-name="place">Place name</button></div><div id="generator-output" class="generator-output section"></div></div><div><h2>Focus mode</h2><p class="muted small">Hides navigation and secondary chrome while you work on the current surface.</p><button class="button" data-toggle-focus="1">Toggle focus mode</button></div></div></section>`;
    document.querySelector('#note-form')?.addEventListener('submit',saveNote); document.querySelector('#task-form')?.addEventListener('submit',saveTask); document.querySelector('#saved-view-form')?.addEventListener('submit',saveView); document.querySelector('#dashboard-widgets-form')?.addEventListener('submit',saveDashboardWidgets); document.querySelector('#manuscript-scene')?.addEventListener('input',e=>renderManuscriptEditor(e.target.value)); document.querySelector('#whiteboard-edge-form')?.addEventListener('submit',saveWhiteboardEdge); bindWhiteboardDrag();
  }
  function workspaceRow(item,status){const target=entityById(item.data?.targetId);return `<div class="tracking-row"><div><strong>${esc(item.title)}</strong><div class="list-meta">${esc(status)}${target?` • ${esc(target.name)}`:''}</div>${item.data?.body?`<div class="small">${esc(item.data.body)}</div>`:''}</div><div class="actions">${['contextNote','task'].includes(item.kind)?`<button class="button ghost" data-toggle-workspace="${esc(item.id)}">${item.kind==='task'?(item.data?.done?'Reopen':'Done'):(item.data?.resolved?'Reopen':'Resolve')}</button>`:''}${item.kind==='contextNote'?`<button class="button ghost" data-convert-note="${esc(item.id)}">Convert</button>`:''}<button class="tiny-x" data-delete-workspace="${esc(item.id)}">×</button></div></div>`;}
  async function saveNote(event){event.preventDefault();await putOne('workspace',workspaceRecord('contextNote',document.querySelector('#note-title').value.trim(),{targetId:document.querySelector('#note-target').value||null,body:document.querySelector('#note-body').value.trim(),resolved:false}));await refreshState();renderWorkbench();}
  async function saveTask(event){event.preventDefault();await putOne('workspace',workspaceRecord('task',document.querySelector('#task-title').value.trim(),{targetId:document.querySelector('#task-target').value||null,due:document.querySelector('#task-due').value.trim(),done:false}));await refreshState();renderWorkbench();}
  async function saveView(event){event.preventDefault();await putOne('workspace',workspaceRecord('savedView',document.querySelector('#saved-view-name').value.trim(),{route:document.querySelector('#saved-view-route').value}));await refreshState();renderWorkbench();}
  async function saveDashboardWidgets(event){event.preventDefault();const project=structuredClone(projectSetting());project.dashboardWidgets=[...event.target.querySelectorAll('input:checked')].map(x=>x.value);await putOne('settings',{key:'project',value:project});await refreshState();toast('Dashboard layout saved.');}
  function renderManuscriptEditor(sceneId){const out=document.querySelector('#manuscript-editor');if(!out)return;const scene=entityById(sceneId);if(!scene){out.innerHTML='<div class="muted small">Choose a scene.</div>';return;}const body=scene.fields?.manuscriptText||'';out.innerHTML=`<form id="manuscript-form"><div class="section-title"><div><strong>${esc(storyPath(scene,state.entities))}</strong><div class="muted small" id="manuscript-count">${wordCount(body)} words</div></div><button class="button primary" type="submit">Save draft</button></div><textarea id="manuscript-body" class="manuscript-textarea" rows="20">${esc(body)}</textarea><div class="actions section"><button class="button ghost" type="button" data-export-manuscript="${esc(scene.id)}">Export scene text</button></div></form>`;document.querySelector('#manuscript-body')?.addEventListener('input',e=>document.querySelector('#manuscript-count').textContent=`${wordCount(e.target.value)} words`);document.querySelector('#manuscript-form')?.addEventListener('submit',async e=>{e.preventDefault();const current=entityById(scene.id);try{await putOne('entities',{...current,fields:{...current.fields,manuscriptText:document.querySelector('#manuscript-body').value},updatedAt:now()},{baseUpdatedAt:current.updatedAt});await refreshState();renderManuscriptEditor(scene.id);toast('Scene manuscript saved.');}catch(err){toast(err.message);}});}
  function wordCount(value){return String(value||'').trim()?String(value).trim().split(/\s+/).length:0;}
  function whiteboardHtml(nodes,edges){const byId=new Map(nodes.map(n=>[n.id,n]));return `<svg class="whiteboard-lines" viewBox="0 0 1000 600" preserveAspectRatio="none">${edges.map(e=>{const a=byId.get(e.data?.fromNodeId),b=byId.get(e.data?.toNodeId);if(!a||!b)return'';return `<line x1="${Number(a.data?.x)||100}" y1="${Number(a.data?.y)||100}" x2="${Number(b.data?.x)||200}" y2="${Number(b.data?.y)||200}"/><text x="${((Number(a.data?.x)||100)+(Number(b.data?.x)||200))/2}" y="${((Number(a.data?.y)||100)+(Number(b.data?.y)||200))/2}">${esc(e.title||'')}</text>`;}).join('')}</svg>${nodes.map(n=>`<article class="whiteboard-node" data-whiteboard-node="${esc(n.id)}" style="left:${Number(n.data?.x)||80}px;top:${Number(n.data?.y)||80}px"><strong>${esc(n.title)}</strong>${n.data?.body?`<div class="small">${esc(n.data.body)}</div>`:''}${n.data?.linkedEntityId?`<div class="small">${esc(entityById(n.data.linkedEntityId)?.name||'Missing entry')}</div>`:''}<button class="tiny-x" data-delete-workspace="${esc(n.id)}">×</button></article>`).join('')}`;}
  async function addWhiteboardNode(){const title=prompt('Whiteboard card title');if(!title?.trim())return;const body=prompt('Note (optional)')||'';const linkName=(prompt('Optional: exact name of an existing entry to link')||'').trim();const linked=linkName?activeEntities().find(e=>e.name.toLowerCase()===linkName.toLowerCase()):null;await putOne('workspace',workspaceRecord('whiteboardNode',title.trim(),{body,x:100+Math.floor(Math.random()*500),y:80+Math.floor(Math.random()*300),linkedEntityId:linked?.id||null}));await refreshState();renderWorkbench();}
  async function saveWhiteboardEdge(event){event.preventDefault();const from=document.querySelector('#edge-from').value,to=document.querySelector('#edge-to').value;if(from===to)return toast('Choose two different cards.');await putOne('workspace',workspaceRecord('whiteboardEdge',document.querySelector('#edge-label').value.trim(),{fromNodeId:from,toNodeId:to}));await refreshState();renderWorkbench();}
  function bindWhiteboardDrag(){let active=null,offsetX=0,offsetY=0;document.querySelectorAll('[data-whiteboard-node]').forEach(node=>node.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;active=node;const rect=node.getBoundingClientRect();offsetX=e.clientX-rect.left;offsetY=e.clientY-rect.top;node.setPointerCapture?.(e.pointerId);}));document.querySelector('#whiteboard')?.addEventListener('pointermove',e=>{if(!active)return;const board=e.currentTarget.getBoundingClientRect();active.style.left=`${Math.max(0,Math.min(board.width-active.offsetWidth,e.clientX-board.left-offsetX))}px`;active.style.top=`${Math.max(0,Math.min(board.height-active.offsetHeight,e.clientY-board.top-offsetY))}px`;});document.querySelector('#whiteboard')?.addEventListener('pointerup',async e=>{if(!active)return;const item=state.workspace.find(w=>w.id===active.dataset.whiteboardNode),x=parseFloat(active.style.left),y=parseFloat(active.style.top);active=null;if(item){await putOne('workspace',{...item,data:{...item.data,x,y},updatedAt:now()});await refreshState();renderWorkbench();}});}
  function generatedName(kind){const starts=kind==='place'?['Ael','Cael','Dor','Eld','Fen','Gal','Kor','Lyr','Mor','Ryn','Val','West']:['Ar','Bel','Cor','Dar','Eli','Fen','Ira','Ka','Lor','Mira','Ner','Ser'];const mids=['a','e','i','o','ae','en','ir','or','an','el'];const ends=kind==='place'?['wyn','holm','reach','mere','ford','spire','vale','gard','heim','ara']:['n','r','s','th','len','ria','ric','wen','el','a'];return starts[Math.floor(Math.random()*starts.length)]+mids[Math.floor(Math.random()*mids.length)]+ends[Math.floor(Math.random()*ends.length)];}

  function renderReaderPreview(){
    const points=storyEntities();
    main.innerHTML=ctx.pageHeader('Reader Preview','Preview only the information the reader should know by a selected point. Author truth, secrets, actual mystery answers, and private notes stay out of this view.','')+`<section class="card"><div class="form-grid"><label>Story point<select id="reader-preview-point"><option value="">Choose book / chapter / scene…</option>${points.map(option).join('')}</select></label><div><span class="muted small">Exported preview is a separate static read-only HTML file.</span><div class="actions section"><button class="button" id="export-reader-html" disabled>Export reader HTML</button></div></div></div></section><div id="reader-preview-results" class="section"></div>`;
    document.querySelector('#reader-preview-point')?.addEventListener('input',e=>renderReaderPreviewResults(e.target.value)); document.querySelector('#export-reader-html')?.addEventListener('click',()=>exportReaderHtml(document.querySelector('#reader-preview-point').value));
  }
  function readerVisible(pointId){const direct=state.knowledge.filter(k=>k.knowerKind==='reader'&&(!k.storyEntityId||compareStoryRefs(k.storyEntityId,pointId,state.entities)<=0)),reveals=state.reveals.filter(r=>{const ref=r.sceneId||r.chapterId||r.bookId;return !ref||compareStoryRefs(ref,pointId,state.entities)<=0;});const ids=new Set([...direct.map(k=>k.subjectEntityId),...reveals.map(r=>r.targetEntityId).filter(Boolean)]);return activeEntities().filter(e=>ids.has(e.id)||e.fields?.commonBelief||e.fields?.readerKnowledge).map(e=>({entity:e,reader:direct.filter(k=>k.subjectEntityId===e.id),reveals:reveals.filter(r=>r.targetEntityId===e.id)}));}
  function renderReaderPreviewResults(pointId){const out=document.querySelector('#reader-preview-results'),button=document.querySelector('#export-reader-html');if(!out)return;if(!pointId){out.innerHTML='';if(button)button.disabled=true;return;}if(button)button.disabled=false;const rows=readerVisible(pointId);out.innerHTML=rows.length?`<div class="reader-site"><header><div class="eyebrow">READER VIEW • ${esc(storyPath(entityById(pointId),state.entities))}</div><h2>${esc(projectSetting().name||'World')}</h2></header>${rows.map(({entity,reader,reveals})=>`<article class="reader-article"><div class="eyebrow">${esc(typeLabel(entity.type))}</div><h3>${esc(entity.name)}</h3>${entity.summary?`<p>${esc(entity.summary)}</p>`:''}${entity.fields?.commonBelief?`<p>${esc(entity.fields.commonBelief)}</p>`:''}${entity.fields?.readerKnowledge?`<p>${esc(entity.fields.readerKnowledge)}</p>`:''}${reader.map(k=>`<p>${esc(k.belief)}</p>`).join('')}${reveals.map(r=>`<p>${esc(r.readerKnowledge||r.summary||'')}</p>`).join('')}</article>`).join('')}</div>`:'<section class="card"><div class="empty-state"><strong>No reader-safe structured information yet</strong><div>Add reader Knowledge records, Reveals, or reader-facing/common-belief fields.</div></div></section>';}
  function exportReaderHtml(pointId){if(!pointId)return;const rows=readerVisible(pointId);const body=rows.map(({entity,reader,reveals})=>`<article><h2>${escapeStandalone(entity.name)}</h2>${entity.summary?`<p>${escapeStandalone(entity.summary)}</p>`:''}${entity.fields?.commonBelief?`<p>${escapeStandalone(entity.fields.commonBelief)}</p>`:''}${entity.fields?.readerKnowledge?`<p>${escapeStandalone(entity.fields.readerKnowledge)}</p>`:''}${reader.map(k=>`<p>${escapeStandalone(k.belief)}</p>`).join('')}${reveals.map(r=>`<p>${escapeStandalone(r.readerKnowledge||r.summary||'')}</p>`).join('')}</article>`).join('');const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeStandalone(projectSetting().name||'Reader Preview')}</title><style>body{font-family:system-ui,sans-serif;max-width:850px;margin:0 auto;padding:32px;background:#111;color:#eee;line-height:1.6}article{border-top:1px solid #444;padding:24px 0}h1,h2{line-height:1.2}</style></head><body><h1>${escapeStandalone(projectSetting().name||'Reader Preview')}</h1><p>Reader knowledge through ${escapeStandalone(storyPath(entityById(pointId),state.entities))}</p>${body}</body></html>`;downloadBlob(new Blob([html],{type:'text/html'}),`${(projectSetting().name||'world').toLowerCase().replace(/[^a-z0-9]+/g,'-')}-reader-preview.html`);toast('Reader HTML exported.');}
  function escapeStandalone(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}

  function revisionHistoryHtml(entityId){
    const revisions=revisionCache.get(entityId); if(!revisions) return '<div class="muted small">Loading revision history…</div>';
    return revisions.length?`<div class="tracking-list">${revisions.slice(0,12).map(r=>`<details class="revision"><summary>${esc(new Date(r.createdAt).toLocaleString())}${r.data?.changedBy?` • ${esc(r.data.changedBy)}`:''}</summary><div class="prose small">${text(r.data?.snapshot?.summary||'No summary in this revision.')}</div><button class="button ghost section" data-restore-revision="${esc(r.id)}">Restore this revision into the editor</button></details>`).join('')}</div>`:'<div class="muted small">No previous revisions yet. V3 records them automatically when saved entries change.</div>';
  }
  async function loadEntryRevisions(entityId){
    if(!entityId)return; try{ const revisions=await getEntityRevisions(entityId,{limit:50}); revisionCache.set(entityId,revisions); const host=document.querySelector(`[data-revision-history="${CSS.escape(entityId)}"]`); if(host)host.innerHTML=revisionHistoryHtml(entityId); }catch(error){ console.error(error); const host=document.querySelector(`[data-revision-history="${CSS.escape(entityId)}"]`); if(host)host.innerHTML='<div class="muted small">Revision history could not be loaded.</div>'; }
  }
  function renderEntryEnhancements(entity){
    const refs=backlinksFor(entity.id,data()),suggestions=crossLinkSuggestions(entity,activeEntities()).filter(s=>!state.relations.some(r=>(r.fromId===entity.id&&r.toId===s.id)||(r.toId===entity.id&&r.fromId===s.id))),prompts=PROMPTS[entity.type]||[]; let special='';
    if(entity.type==='scene'){const info=sceneContinuity(entity.id,data());if(info)special+=`<section class="detail-section"><h3>Scene Continuity</h3>${sceneDashboardHtml(info)}<div class="actions section"><a class="button ghost" href="#/continuity">Open full continuity workspace</a></div></section>`;}
    if(entity.type==='location'){const u=locationUsage(entity.id,data());special+=`<section class="detail-section"><h3>Location usage</h3><div class="continuity-grid"><div><span class="muted small">Scenes</span><strong>${u.scenes.length}</strong></div><div><span class="muted small">Events</span><strong>${u.events.length}</strong></div><div><span class="muted small">Characters</span><strong>${u.characters.length}</strong></div><div><span class="muted small">Child locations</span><strong>${u.children.length}</strong></div></div></section>`;}
    return `${special}<section class="detail-section"><div class="section-title"><div><h3>Referenced By / Impact</h3><div class="muted small">Structured records that depend on this entry.</div></div></div>${refs.length?`<div class="tracking-list">${refs.slice(0,20).map(impactRow).join('')}</div>`:'<div class="muted small">No backlinks yet.</div>'}</section>${suggestions.length?`<section class="detail-section"><h3>Cross-link suggestions</h3><div class="muted small">Names detected in this entry. Confirm links manually.</div><div class="actions section">${suggestions.slice(0,8).map(s=>`<button class="button ghost" data-suggest-link-from="${esc(entity.id)}" data-suggest-link-to="${esc(s.id)}">Link ${esc(s.name)}</button>`).join('')}</div></section>`:''}${prompts.length?`<section class="detail-section"><h3>Optional completeness hints</h3><ul class="prompt-list">${prompts.map(p=>`<li>${esc(p)}</li>`).join('')}</ul></section>`:''}<section class="detail-section"><h3>Revision history</h3><div data-revision-history="${esc(entity.id)}">${revisionHistoryHtml(entity.id)}</div></section>`;
  }

  async function handleClick(target){
    if(target.dataset.addPlotBeat){await addPlotBeat(target.dataset.sceneId,target.dataset.threadId);return true;}
    if(target.dataset.deleteWorkspace){const item=state.workspace.find(w=>w.id===target.dataset.deleteWorkspace);if(item?.kind==='plotThread'&&state.workspace.some(w=>w.kind==='plotBeat'&&w.data?.threadId===item.id)){toast('Delete or move this thread’s plot beats first.');return true;}if(confirm('Delete this workspace item?')){await deleteOne('workspace',target.dataset.deleteWorkspace);await refreshState();renderRoute();}return true;}
    if(target.dataset.toggleWorkspace){const item=state.workspace.find(w=>w.id===target.dataset.toggleWorkspace);if(item){const dataValue={...item.data};if(item.kind==='task')dataValue.done=!dataValue.done;if(item.kind==='contextNote')dataValue.resolved=!dataValue.resolved;await putOne('workspace',{...item,data:dataValue,updatedAt:now()});await refreshState();renderRoute();}return true;}
    if(target.dataset.openSavedView){const item=state.workspace.find(w=>w.id===target.dataset.openSavedView);if(item)setRoute(item.data?.route||'dashboard');return true;}
    if(target.dataset.convertNote){const item=state.workspace.find(w=>w.id===target.dataset.convertNote);if(item){const type=(prompt('Convert note to: idea, question, or lore','idea')||'').trim().toLowerCase();if(['idea','question','lore'].includes(type)){const prefill={id:id(),type,name:item.title,summary:item.data?.body||'',status:type==='idea'?'Inbox':type==='question'?'Open':'Concept',tags:[],favorite:false,fields:{},notes:'Converted from a contextual scratch note.',createdAt:now(),updatedAt:now()};openEntryEditor(type,null,prefill);}}return true;}
    if(target.dataset.addWhiteboardNode){await addWhiteboardNode();return true;}
    if(target.dataset.generateName){const value=generatedName(target.dataset.generateName);const out=document.querySelector('#generator-output');if(out)out.innerHTML=`<strong>${esc(value)}</strong>`;return true;}
    if(target.dataset.toggleFocus){document.body.classList.toggle('focus-mode');return true;}
    if(target.dataset.exportManuscript){const scene=entityById(target.dataset.exportManuscript);if(scene)downloadBlob(new Blob([scene.fields?.manuscriptText||''],{type:'text/plain'}),`${scene.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.txt`);return true;}
    if(target.dataset.suggestLinkFrom){await putOne('relations',{id:id(),fromId:target.dataset.suggestLinkFrom,toId:target.dataset.suggestLinkTo,type:'related_to',note:'Suggested from text mention',createdAt:now()});await refreshState();renderRoute();toast('Structured link added.');return true;}
    if(target.dataset.restoreRevision){const revision=[...revisionCache.values()].flat().find(w=>w.id===target.dataset.restoreRevision),snap=revision?.data?.snapshot,current=snap?entityById(snap.id):null;if(snap&&current)openEntryEditor(snap.type,null,{...snap,updatedAt:current.updatedAt});return true;}
    return false;
  }

  function bindGlobal(){
    document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();const input=document.querySelector('#global-search');input?.focus();input?.select();}if(e.key==='Escape'&&document.body.classList.contains('focus-mode'))document.body.classList.remove('focus-mode');});
  }

  return {renderContinuity,renderPlotGrid,renderWorldTools,renderWorkbench,renderReaderPreview,renderEntryEnhancements,loadEntryRevisions,handleClick,bindGlobal};
}
